### PR TITLE
build: version bump to 0.16

### PR DESCRIPTION
**Pull request by 96malhar**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by philasmar** [comment]
why did you close the auto PR ?

**Comment by 96malhar** [comment]
> why did you close the auto PR ?

The auto PR was waiting for the build to finish for a prolonged period despite the build being finished

**Comment by 96malhar** [comment]
Closing this PR since https://github.com/aws/aws-dotnet-deploy/pull/291 has been reopened

**Comment by philasmar** [comment]
> > why did you close the auto PR ?
> 
> The auto PR was waiting for the build to finish for a prolonged period despite the build being finished

Closing and reopening the PR fixes the issue

**Pull request closed without merging**
